version: '3'
services:
  pancaketrade:
    image: vbersier/pancaketrade:latest
    build:
      context: .
    restart: unless-stopped
    container_name: pancaketrade
    tty: true
    env_file: .env
    volumes:
      - type: bind
        source: ./user_data
        target: /app/user_data
