---
bsc_rpc: regex("^(https?://.*):(\d*)\/?(.*)$", 'URI')
wallet: regex('^0x[a-fA-F0-9]{40}$', 'ethereum address')
min_pool_size_bnb: num(min=0.0001)
monitor_interval: num(min=1)
update_messages: bool(required=False)
secrets:
  telegram_token: regex('[0-9]{9,}:[a-zA-Z0-9_-]{35}', 'telegram token')
  admin_chat_id: int(min=1)
  wallet_key_id: regex('^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$', 'ethereum address key')