name: Docker Image CI

on:
  push:
    branches: [develop]
    tags: ['v*.*.*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get image tag
        id: image_tag
        run: |
          # Strip git ref prefix from ref
          TAG=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          LATEST=""
          # Strip "v" prefix from tag name if we're dealing with a version tag and tag as latest
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && TAG=$(echo $TAG | sed -e 's/^v//') && LATEST=",vbersier/pancaketrade:latest"
          echo "::set-output name=tag::$TAG"
          echo "::set-output name=latest::$LATEST"
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          pull: true
          push: true
          no-cache: true
          tags: vbersier/pancaketrade:${{ steps.version_tag.outputs.tag }}${{ steps.version_tag.outputs.latest }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
